"""EuroBowl 2026 — grupo 2 (tiers 3-4)."""

ANDY = "[AndyDavo — Eurobowl Ruleset Review 2026](https://www.youtube.com/watch?v=wrmKRBFNqcM) (abr. 2026, reglamento preliminar)"

TEAMS = [
    dict(slug="humanos", name="Humanos", img="humanos.webp",
         fuente=ANDY + " con los avances de [Artemis Black — Road to Eurobowl 2026](https://www.youtube.com/watch?v=yI7pBwzeecE) (sep. 2026), adaptada al presupuesto actual.",
         rr=3, apo=True, ac=1, cheer=0, induc=[], stars=[],
         players=[("Ogre", 1, ["Defensa"]),
                  ("Blitzer", 1, ["Golpe mortífero"]), ("Blitzer", 1, ["Defensa"]),
                  ("Catcher", 1, ["Forcejear"]), ("Catcher", 1, ["Placar"]),
                  ("Thrower", 1, ["Placar"]),
                  ("Línea", 1, ["Forcejear"]), ("Línea", 5, []),
                  ("Halfling", 1, [])],
         nota="El Capitán del equipo da Profesional gratis a un jugador (AndyDavo lo pone en un Catcher).",
         tactica=["Ogro + 3 RR + apotecario: base de AndyDavo; el Tier 3 actual tiene el mismo presupuesto que el reglamento de abril.",
                  "Avances según Artemis Black: Golpe mortífero en un Blitzer y Defensa en el otro (AndyDavo ponía Defensa en ambos).",
                  "Catchers con Forcejear y Placar en lugar del stack Furia + Forcejear; los 30k de Flowing van a un Línea con Forcejear."]),
    dict(slug="hombres-lagarto", name="Hombres Lagarto", img="hombres-lagarto.webp",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=2, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("Kroxigor", 1, []),
                  ("Saurio", 4, ["Placar"]), ("Saurio", 1, ["Forcejear"]), ("Saurio", 1, ["Furia"]),
                  ("Eslizón Línea", 4, [])],
         tactica=["Seis Saurios: cuatro con Placar, uno con Forcejear y uno con Furia para limpiar el campo.",
                  "Sin cambios respecto a la build de AndyDavo: el Tier 3 actual mantiene 1.080k/160k y los 30k de Flowing cubren el exceso del equipo (1.110k).",
                  "Solo 11 jugadores: el apotecario es imprescindible."]),
    dict(slug="no-muertos", name="No Muertos", img="no-muertos.webp",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=4, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Momia", 2, ["Defensa"]),
                  ("Caballero", 1, ["Golpe mortífero"]), ("Caballero", 1, ["Defensa"]),
                  ("Necrófago", 2, ["Forcejear"]),
                  ("Zombie", 6, [])],
         tactica=["Momias con Defensa, un Caballero con Golpe mortífero y otro con Defensa, Necrófagos con Forcejear: avances de AndyDavo intactos.",
                  "Pasa de Tier 2 a Tier 3: 70k más de equipo y 20k más de Skill Gold que cubren el exceso que tenía con el reglamento de abril.",
                  "El presupuesto extra paga una cuarta segunda oportunidad (70k) con Flowing; equipo lento sin apotecario que vive de las RR."]),
    dict(slug="vampiros", name="Vampiros",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=3, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Blitzer Vampiro", 1, ["Furia"]), ("Blitzer Vampiro", 1, ["Robar balón"]),
                  ("Lanzador Vampiro", 1, ["Líder"]), ("Lanzador Vampiro", 1, ["Placar"]),
                  ("Corredor Vampiro", 2, ["Esquivar"]),
                  ("Thrall (Línea)", 1, ["Forcejear"]), ("Thrall (Línea)", 6, [])],
         tactica=["Seis vampiros sin Vargheist; siete Thralls para alimentar la Sed de sangre.",
                  "Sin cambios: el Tier 3 actual coincide con el de abril y los 30k de Flowing cubren 20k de equipo y 10k de Skill Gold.",
                  "Sin apotecario (no cabe); Regeneración en todos los vampiros."]),
    dict(slug="nigromantes", name="Nigromantes",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=2, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Flesh Golem", 2, ["Defensa"]), ("Wraith", 2, ["Defensa"]),
                  ("Werewolf", 2, ["Placar"]),
                  ("Ghoul", 1, ["Forcejear"]), ("Ghoul", 1, []),
                  ("Zombie Línea", 5, [])],
         tactica=["Cuatro Defensas (Golems y Wraiths) y Hombres lobo con Placar para Furia + Garras.",
                  "Sube de Tier 3 a Tier 4: +20k de equipo y +30k de Skill Gold. Se añade un quinto Zombie (13 jugadores, sin apotecario) y el segundo Hombre lobo cambia Forcejear por Placar.",
                  "Una tercera RR (70k) no cabía sin quitar un jugador; se prioriza profundidad de banquillo."]),
    dict(slug="nordicos", name="Nórdicos", img="nordicos.webp",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=3, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("Ulfwerener", 2, ["Defensa"]),
                  ("Valkyrie", 1, ["Forcejear"]), ("Valkyrie", 1, ["Placar"]),
                  ("Berserker", 1, ["Defensa"]), ("Berserker", 1, ["Golpe mortífero"]),
                  ("Línea", 1, ["Defensa"]), ("Línea", 4, []),
                  ("Cerdo Cervecero", 2, [])],
         tactica=["Mismo equipo que AndyDavo: 3 RR, apotecario y dos Cerdos Cerveceros.",
                  "Sube de Tier 3 a Tier 4: los 1.100k ya no exceden el presupuesto y sobran 50k de Skill Gold (30k de Flowing).",
                  "Ese margen paga Defensa como secundaria en un Línea: tercer jugador con Defensa y Placar en la línea."]),
    dict(slug="nurgle", name="Nurgle",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=3, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Rotspawn", 1, ["Defensa"]), ("Bloater", 4, ["Placar"]),
                  ("Pestigor", 1, ["Forcejear"]), ("Pestigor", 1, ["Placar"]),
                  ("Rotter", 1, ["Forcejear"]), ("Rotter", 4, [])],
         tactica=["Cuatro Bloaters con Placar y Rotspawn con Defensa: muro lento de AV10 y Regeneración.",
                  "Sin cambios: Nurgle sigue en Tier 4 con el mismo presupuesto; los 30k de Flowing cubren el exceso de Skill Gold (220/190).",
                  "Sin apotecario (no disponible)."]),
    dict(slug="slann", name="Slann", img="slann.webp",
         fuente=ANDY + ", adaptada al presupuesto actual.",
         rr=4, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Kroxigor", 1, []),
                  ("Slann Catcher", 1, ["Esquivar"]), ("Slann Catcher", 1, ["Defensa"]),
                  ("Slann Línea", 4, ["Forcejear"]), ("Slann Línea", 1, ["Robar balón", "Forcejear"]),
                  ("Slann Línea", 5, [])],
         tactica=["Kroxigor, dos Catchers y diez Líneas con 4 RR; sin Blitzers ni apotecario, como en la build de AndyDavo.",
                  "Cinco Líneas con Forcejear (uno en stack con Robar balón) y Defensa como secundaria en un Catcher.",
                  "Sin cambios: Slann sigue en Tier 4; quedan 10k de Flowing sin uso."]),
]
