"""EuroBowl 2026 — grupo 4: Bretonia, Renegados del Caos, Gnomos, Goblins, Halflings, Khorne, Ogros."""

ANDY = "[AndyDavo — Eurobowl Ruleset Review 2026](https://www.youtube.com/watch?v=wrmKRBFNqcM) (abr. 2026, reglamento preliminar)"

TEAMS = [
    dict(slug="bretonia", name="Bretonia", img="bretonia.webp",
         fuente=f"{ANDY}, adaptada al presupuesto actual.",
         rr=3, apo=True, ac=2, cheer=2,
         players=[("Caballero del Grial", 2, ["Defensa"]),
                  ("Caballero Receptor", 2, ["Placar", "Esquivar"]),
                  ("Caballero Lanzador", 1, ["Forcejear"]),
                  ("Caballero Lanzador", 1, ["Placar"]),
                  ("Escuderos", 1, ["Placar"]),
                  ("Escuderos", 6, [])],
         tactica=["Los seis caballeros llevan el peso: Defensa en los del Grial y stack Placar + Esquivar en los Receptores.",
                  "Cambio frente al reglamento de abril: Bretonia pasa al tier 6 (+20k de equipo y +20k de Skill Gold). Los 30k de Flowing Funds que sobran pagan Placar para un Escudero.",
                  "Los 20k de equipo sobrantes van a 2 animadoras: no alcanzan para un cuarto reroll."]),
    dict(slug="renegados-del-caos", name="Renegados del Caos",
         fuente=f"{ANDY}, adaptada al presupuesto actual.",
         rr=2, apo=True, ac=1,
         players=[("Ogro Renegado", 1, ["Defensa"]),
                  ("Rata Ogro Renegada", 1, ["Placar"]),
                  ("Troll Renegado", 1, ["Defensa"]),
                  ("Elfo Oscuro Renegado", 1, ["Placar", "Esquivar"]),
                  ("Lanzador Humano Renegado", 1, ["Líder"]),
                  ("Orco Renegado", 1, []),
                  ("Skaven Renegado", 1, ["Placar"]),
                  ("Línea Humano Renegado", 2, ["Forcejear"]),
                  ("Línea Humano Renegado", 3, []),
                  ("Goblin Renegado", 1, [])],
         tactica=["Tres grandullones: Defensa en el Ogro y el Troll, y Placar (secundaria) en la Rata Ogro. El Elfo Oscuro lleva el stack Placar + Esquivar.",
                  "Cambio frente al reglamento de abril: en el tier 6 entra completa con 15k de equipo de margen. Se suma Placar al Skaven Renegado (30k de Flowing) y un ayudante del entrenador.",
                  "No hay presupuesto para un tercer reroll a 70k: costaría 55k de Flowing y el máximo es 40k."]),
    dict(slug="gnomos", name="Gnomos", img="gnomos.webp",
         fuente=f"{ANDY}; el tier 6 no cambia en el reglamento actual y la lista se mantiene igual.",
         rr=5, apo=True, ac=1,
         players=[("Hombre Árbol del Bosque de Altern", 1, ["Defensa"]),
                  ("Hombre Árbol del Bosque de Altern", 1, ["Ojo de halcón"]),
                  ("Gnomo Domador de Bestias (Beastmaster)", 2, ["Esquivar"]),
                  ("Gnomo Ilusionista", 2, ["Esquivar"]),
                  ("Zorro del Bosque (Woodland Fox)", 2, []),
                  ("Gnomo Línea", 3, ["Esquivar"]),
                  ("Gnomo Línea", 1, ["Placaje heroico"]),
                  ("Gnomo Línea", 3, [])],
         tactica=["Cinco rerolls a 50k: el equipo depende de repetir tiradas.",
                  "Esquivar en siete gnomos y Ojo de halcón en un Hombre Árbol para lanzar compañeros.",
                  "Sin cambios frente al reglamento de abril: el tier 6 conserva las cifras (1.140k / 240k / 40k). Los 40k de Flowing van al Skill Gold."]),
    dict(slug="goblins", name="Goblins",
         fuente="Diseño propio a partir de la ficha BB2025 de `source/teams/goblins.md`: no hay captura de AndyDavo para este equipo.",
         rr=3, apo=True,
         induc=[("Sobornos", 2)],
         players=[("Troll Entrenado", 2, ["Placar"]),
                  ("Pogo saltarín", 1, ["Echarse a un lado"]),
                  ("Doom Diver", 1, []),
                  ("Fanático", 1, ["Golpe mortífero"]),
                  ("Looney", 1, []),
                  ("Bomma", 1, ["Precisión"]),
                  ("'Ooligan", 1, ["Furtivo"]),
                  ("Goblin Línea", 2, ["Placaje heroico"]),
                  ("Goblin Línea", 1, ["Echarse a un lado"]),
                  ("Goblin Línea", 3, [])],
         tactica=["Dos Trolls con Placar (secundaria) para que la doble calavera no los tumbe. Las armas secretas se cubren con 2 Sobornos (50k cada uno por Sobornos y corrupción).",
                  "Golpe mortífero en el Fanático, Furtivo en el 'Ooligan y Precisión en el Bomma. El Pogo con Echarse a un lado lleva el balón.",
                  "14 jugadores, 3 rerolls y apotecario. Se usan 15k de Flowing en equipo y 10k en Skill Gold."]),
    dict(slug="halflings", name="Halflings", img="halflings.webp",
         fuente=f"{ANDY} (opción Veterans), adaptada al presupuesto actual.",
         rr=1, apo=False, induc=[("Chef Maestro Halfling", 1)],
         stars=[("Grombrindal", 170, "Veteran"), ("Rumbelow Sheepskin", 170, "Veteran")],
         players=[("Hombre Árbol del Bosque de Athel", 1, ["Ojo de halcón"]),
                  ("Hombre Árbol del Bosque de Athel", 1, ["Defensa"]),
                  ("Halfling Catcher", 2, ["Pies firmes"]),
                  ("Halfling Hefty", 1, ["Líder"]),
                  ("Halfling Hefty", 1, ["Placaje heroico"]),
                  ("Halfling Hopeful Línea", 1, ["Placaje heroico"]),
                  ("Halfling Hopeful Línea", 6, [])],
         tactica=["Grombrindal y Rumbelow Sheepskin como Veterans (recargo de 40k cada uno). Con estrellas no se permiten secundarias ni stacks: todos los avances son primarios.",
                  "Igual que la captura de AndyDavo: 1 reroll + Chef Maestro Halfling (100k por la Copa Dedal Halfling), que genera rerolls extra cada parte."]),
    dict(slug="khorne", name="Khorne", img="khorne.png",
         fuente=f"{ANDY}, adaptada al presupuesto actual.",
         rr=3, apo=True,
         players=[("BloodSpawn", 1, ["Imparable"]),
                  ("Bloodseekers", 4, ["Placar"]),
                  ("Khorngors", 1, ["Placar", "Placaje defensivo"]),
                  ("Khorngors", 1, ["Forcejear"]),
                  ("Líneas Marauder Nacidos de la Sangre", 1, ["Placar"]),
                  ("Líneas Marauder Nacidos de la Sangre", 1, ["Forcejear"]),
                  ("Líneas Marauder Nacidos de la Sangre", 2, [])],
         nota="Solo 11 jugadores. Un duodécimo Marauder obligaría a quitar un reroll.",
         tactica=["Los 4 Bloodseekers con Furia + Placar y el BloodSpawn con Imparable sostienen el plan.",
                  "Cambio frente al reglamento de abril: el tier 6 da 20k más de Skill Gold. Con esos 20k y 30k de Flowing (10k cubren el exceso de equipo), dos Marauders reciben Placar y Forcejear."]),
    dict(slug="ogros", name="Ogros", img="ogros.webp",
         fuente=f"{ANDY}, adaptada al presupuesto actual (tier 7).",
         rr=3, apo=False,
         players=[("Ogre Blocker", 3, ["Placar"]),
                  ("Ogre Blocker", 1, ["Defensa", "Abrirse paso"]),
                  ("Ogre Blocker", 1, ["Abrirse paso"]),
                  ("Ogre Runt Punter", 1, ["Líder"]),
                  ("Gnoblar Línea", 2, ["Placaje heroico"]),
                  ("Gnoblar Línea", 6, [])],
         tactica=["Placar es secundaria para los Ogros: las 3 secundarias van ahí. Líder en el Runt Punter da un 4.º reroll.",
                  "Cambio frente al reglamento de abril: Ogros sube al tier 7 (+30k de Skill Gold y +10k de Flowing). Un Ogro pasa a llevar el stack Defensa + Abrirse paso y un segundo Gnoblar recibe Placaje heroico.",
                  "Flowing: 25k para el equipo (3 rerolls a 70k) y 20k para Skill Gold, en total 45k de 50k."]),
]
