"""EuroBowl 2026 FINAL — grupo 3: tiers 4-6 (Reyes Funerarios, Caos, Enanos, Unión Élfica, Nobleza, Snotlings, Orcos Negros)."""

ANDY = "[AndyDavo — Eurobowl Ruleset Review 2026](https://www.youtube.com/watch?v=wrmKRBFNqcM) (abr. 2026, BETA)"
ARTEMIS_EU = "[Artemis Black — Road to Eurobowl: Elven Union & HE](https://www.youtube.com/watch?v=GgfTtYKR3Ec) (sep. 2026, roster real de selección)"

TEAMS = [
    dict(slug="reyes-funerarios", name="Reyes Funerarios", img="reyes-funerarios.webp",
         fuente=f"{ANDY}; mismo tier y presupuesto en la FINAL, se mantiene sin cambios.",
         rr=3, apo=False, ac=0, cheer=0, induc=[], stars=[],
         players=[("Guardián de la Tumba (Tomb Guardian)", 3, ["Defensa"]),
                  ("Guardián de la Tumba (Tomb Guardian)", 1, ["Golpe mortífero"]),
                  ("Blitzer de Reyes Funerarios", 1, ["Placaje defensivo"]),
                  ("Blitzer de Reyes Funerarios", 1, ["Furia"]),
                  ("Thrower de Reyes Funerarios", 2, ["Placar"]),
                  ("Esqueleto Línea", 4, [])],
         tactica=["Cuatro Guardianes (tres con Defensa, uno con Golpe mortífero) forman el muro; Regeneración en todo el equipo y sin apotecario (Señores de los No Muertos).",
                  "Placar en los dos Throwers para que el portador aguante; los 30k de Flowing van íntegros al Skill Gold.",
                  "Sin cambios respecto a la build de AndyDavo: el tier 4 conserva 1100k/190k/30k en la FINAL."]),

    dict(slug="elegidos-del-caos", name="Elegidos del Caos", img="Chaos.webp",
         fuente=f"{ANDY}, adaptada al presupuesto FINAL (sube de tier 4 a tier 5).",
         rr=3, apo=True, ac=0, cheer=0, induc=[("Mascota del equipo", 1)], stars=[],
         players=[("Ogro del Caos", 1, ["Defensa"]),
                  ("Guerrero Caos", 4, ["Placar"]),
                  ("Beastman", 1, ["Placar"]),
                  ("Beastman", 2, ["Forcejear"]),
                  ("Beastman", 4, [])],
         tactica=["Placar en los cuatro Guerreros del Caos y Defensa en el Ogro: línea FU4 muy sólida.",
                  "El Skill Gold de la build original (220k) cuadra exacto con el nuevo tier 5.",
                  "Con los 20k extra de equipo más 30k de Flowing se ficha un 12.º jugador (Beastman): AndyDavo jugaba con solo 11."]),

    dict(slug="enanos-del-caos", name="Enanos del Caos",
         fuente=f"{ANDY}; mismo tier y presupuesto en la FINAL, se mantiene sin cambios.",
         rr=2, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("Minotauro Esclavizado", 1, ["Defensa"]),
                  ("Bull Centaur", 2, ["Abrirse paso", "Forcejear"]),
                  ("Enano del Caos Blocker", 1, ["Golpe mortífero"]),
                  ("Enano del Caos Blocker", 3, ["Defensa"]),
                  ("Flamesmith", 2, []),
                  ("Hobgoblin Línea", 2, [])],
         nota="Solo 11 jugadores: todo el presupuesto va a posicionales caros. El Flowing (30k) se gasta en Skill Gold.",
         tactica=["Bull Centaurs con stack Abrirse paso + Forcejear: corredores FU4 difíciles de parar.",
                  "Defensa en Minotauro y tres Blockers; Golpe mortífero en el cuarto. Los Flamesmith aportan Exhalar fuego.",
                  "Sin cambios: tier 5 en BETA y en FINAL (1120k/220k/30k)."]),

    dict(slug="enanos", name="Enanos", img="enanos.webp",
         fuente=f"{ANDY}, adaptada al presupuesto FINAL (sube de tier 4 a tier 5).",
         rr=2, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("MataTrols", 1, ["Golpe mortífero"]),
                  ("MataTrols", 1, ["Defensa"]),
                  ("Enano Blitzer", 2, ["Defensa"]),
                  ("Enano Runner", 1, ["Placar"]),
                  ("Enano Runner", 1, ["Líder"]),
                  ("Enano Línea", 1, ["Defensa"]),
                  ("Enano Línea", 5, [])],
         tactica=["Defensa en un MataTrols, los dos Blitzers y un Línea (secundaria); Líder en un Runner para el tercer reroll efectivo.",
                  "El Skill Gold original (220k) cuadra exacto con el tier 5.",
                  "Cambio: se quita la Mascota del equipo y se ficha un 12.º Enano Línea con los 20k extra + Flowing; alternativa: tercer reroll (60k) en lugar del Línea."]),

    dict(slug="union-elfica", name="Unión Élfica", img="union-elfica.webp",
         fuente=f"{ANDY}, ajustada con {ARTEMIS_EU}.",
         rr=2, apo=True, ac=1, cheer=0, induc=[], stars=[],
         players=[("Elfo Blitzer", 1, ["Esquivar"]),
                  ("Elfo Blitzer", 1, ["Esquivar", "Placaje heroico"]),
                  ("Elfo Catcher", 1, ["Esquivar", "Echarse a un lado"]),
                  ("Elfo Catcher", 1, ["Esquivar"]),
                  ("Elfo Lanzador", 1, ["Líder"]),
                  ("Elfo Línea", 1, ["Esquivar"]),
                  ("Elfo Línea", 1, ["Forcejear"]),
                  ("Elfo Línea", 5, [])],
         tactica=["Esquivar en los dos Blitzers y los dos Catchers, y Líder en el Lanzador (con solo 2 rerolls), como en el roster real comentado por Artemis Black.",
                  "Stack Esquivar + Echarse a un lado en un Catcher (Artemis) y Esquivar + Placaje heroico en un Blitzer (AndyDavo).",
                  "Cambio frente a AndyDavo: se sustituyen los stacks Placar + Esquivar y Furia + Forcejear de los Catchers por más Esquivar (también en un Línea); mismo tier y presupuesto."]),

    dict(slug="nobleza-imperial", name="Nobleza Imperial", img="nobleza-imperial.webp",
         fuente=f"{ANDY}, adaptada al presupuesto FINAL (sube de tier 4 a tier 5).",
         rr=3, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("Ogre", 1, ["Defensa"]),
                  ("Noble Blitzer", 1, ["Esquivar"]),
                  ("Noble Blitzer", 1, ["Furia"]),
                  ("Bodyguard", 4, ["Defensa"]),
                  ("Imperial Thrower", 1, ["Líder"]),
                  ("Retainer Línea", 4, [])],
         tactica=["Defensa en el Ogro y los cuatro Bodyguards: apoyos garantizados en la línea.",
                  "Líder en el Thrower; Blitzers con Esquivar y Furia.",
                  "Cambio: con los 20k extra + Flowing se cambia el Ayudante del entrenador por un tercer reroll; el Skill Gold original (220k) cuadra exacto con el tier 5."]),

    dict(slug="snotlings", name="Snotlings", img="snotlings.webp",
         fuente=f"{ANDY}; mismo tier y presupuesto en la FINAL, se mantiene sin cambios.",
         rr=3, apo=False, ac=0, cheer=0, induc=[("Sobornos", 3), ("Novatos embravecidos", 1)], stars=[],
         players=[("Troll Entrenado", 1, ["Ojo de halcón", "Defensa"]),
                  ("Troll Entrenado", 1, ["Defensa"]),
                  ("Pump Wagon", 1, ["Abrirse paso"]),
                  ("Pump Wagon", 1, ["Crujir"]),
                  ("Stilty Runna", 1, ["Placaje heroico"]),
                  ("Stilty Runna", 1, ["Pies firmes"]),
                  ("Fun-hoppa", 2, ["Placaje heroico"]),
                  ("Snotling Línea", 1, ["Jugar sucio"]),
                  ("Snotling Línea", 7, [])],
         tactica=["Troll con Ojo de halcón + Defensa para lanzar Snotlings con precisión; Pump Wagons con Abrirse paso y Crujir.",
                  "Tres Sobornos (50k con Sobornos y corrupción) y Novatos embravecidos para el plan de faltas y desgaste.",
                  "Sin cambios: tier 5 en BETA y en FINAL; el Flowing cubre 20k de equipo y 10k de Skill Gold."]),

    dict(slug="orcos-negros", name="Orcos Negros", img="orcos-negros.webp",
         fuente=f"{ANDY}, adaptada al presupuesto FINAL (sube de tier 5 a tier 6).",
         rr=4, apo=True, ac=0, cheer=0, induc=[], stars=[],
         players=[("Black Orc", 2, ["Defensa"]),
                  ("Black Orc", 1, ["Placaje defensivo"]),
                  ("Black Orc", 1, ["Placar"]),
                  ("Black Orc", 2, ["Golpe mortífero"]),
                  ("Troll Adiestrado", 1, ["Defensa"]),
                  ("Goblin Bruiser", 1, ["Esprintar", "Pies firmes"]),
                  ("Goblin Bruiser", 4, [])],
         tactica=["Seis Black Orcs con Defensa, Placar, Placaje defensivo y Golpe mortífero; Troll con Defensa.",
                  "Goblin Bruiser con stack Esprintar + Pies firmes como portador/anotador.",
                  "Cambio: el tier 6 da 20k más de equipo, 20k más de Skill Gold y 10k más de Flowing; se invierten en un cuarto reroll (60k) para un equipo AG4+."]),
]
