"""EuroBowl 2026 FINAL — grupo 1 (tiers 1-3: AVM, Orcos, Elfos Silvanos, Amazonas, Skavens, Habitantes, Elfos Oscuros, Altos Elfos)."""

_ANDY = "[AndyDavo — Eurobowl Ruleset Review 2026](https://www.youtube.com/watch?v=wrmKRBFNqcM) (abr. 2026, BETA)"

TEAMS = [
    dict(slug="alianza-viejo-mundo", name="Alianza del Viejo Mundo", img="alianza-viejo-mundo.webp",
         fuente=f"{_ANDY}, adaptada al presupuesto FINAL.",
         rr=2, apo=True, ac=1,
         players=[("Hombre Árbol", 1, []), ("Enano Blitzer", 1, ["Defensa"]), ("Humano Blitzer", 1, ["Golpe mortífero"]),
                  ("Enano Blocker", 3, []), ("Humano Catcher", 1, ["Placar"]), ("Humano Thrower", 1, ["Líder"]),
                  ("Humano Línea", 1, ["Forcejear"]), ("Humano Línea", 3, [])],
         tactica=["Núcleo enano (3 Blockers + Blitzer con Defensa) y Hombre Árbol para aguantar; Humano Blitzer con Golpe mortífero para pegar.",
                  "Catcher con Placar y Thrower con Líder (3.ª segunda oportunidad efectiva).",
                  "Cambio FINAL: el presupuesto sube de 1060k a 1070k; los 15k libres pagan un ayudante del entrenador. Los 10k de Flowing siguen en Skill Gold."]),
    dict(slug="orcos", name="Orcos",
         fuente=f"{_ANDY}, adaptada al presupuesto FINAL (Tier 2 → Tier 1).",
         rr=2, apo=True, ac=1, induc=[("Mascota del equipo", 1)],
         players=[("Troll", 1, ["Defensa"]), ("Big Un Blocker", 2, ["Placar"]), ("Orco Blitzer", 1, ["Placaje defensivo"]),
                  ("Orco Blitzer", 1, []), ("Orco Lanzador", 1, ["Líder"]), ("Orco Lanzador", 1, []),
                  ("Orco Línea", 4, []), ("Goblin", 1, [])],
         nota="El Capitán del equipo (Team Captain) da Profesional gratis a un jugador; AndyDavo lo pone en un Big Un Blocker.",
         tactica=["Big Uns con Placar y Troll con Defensa: línea de choque fiable.",
                  "Cambio FINAL: los Orcos bajan a Tier 1 (Skill Gold 140k → 120k, Flowing 20k → 10k). Se elimina Defensa del segundo Orco Blitzer (−30k) para cuadrar 130k de Skill Gold.",
                  "El presupuesto de equipo (1070k) no cambia: se mantienen Mascota, ayudante, apotecario y 2 segundas oportunidades."]),
    dict(slug="elfos-silvanos", name="Elfos Silvanos", img="elfos-silvanos.webp",
         fuente=f"{_ANDY}, adaptada al presupuesto FINAL.",
         rr=2, apo=True,
         players=[("Wardancer", 1, ["Placaje defensivo"]), ("Wardancer", 1, ["Robar balón"]),
                  ("Elfo Silvano Catcher", 1, ["Echarse a un lado"]), ("Elfo Silvano Catcher", 1, []),
                  ("Elfo Silvano Thrower", 1, ["Líder"]), ("Elfo Silvano Línea", 1, ["Placar"]),
                  ("Elfo Silvano Línea", 1, ["Forcejear"]), ("Elfo Silvano Línea", 4, [])],
         tactica=["Dos Wardancers (Placaje defensivo y Robar balón) para defender; Catcher con Echarse a un lado y Thrower con Líder.",
                  "Cambio FINAL: con 1070k el equipo (1065k) ya cabe sin Flowing, así que los 10k de Flowing pasan a Skill Gold: un Línea cambia Forcejear por Placar."]),
    dict(slug="amazonas", name="Amazonas", img="amazonas.webp",
         fuente=f"{_ANDY}; mismo tier y presupuesto en FINAL, sin cambios.",
         rr=2, apo=True, ac=2,
         players=[("Guerrera Jaguar Blocker", 1, ["Placar"]), ("Guerrera Jaguar Blocker", 1, ["Defensa"]),
                  ("Guerrera Piraña Blitzer", 2, ["Placar"]), ("Guerrera Pitón Thrower", 1, ["Líder"]),
                  ("Guerrera Águila Línea", 1, ["Forcejear"]), ("Guerrera Águila Línea", 7, [])],
         tactica=["Placar en las Pirañas y en una Jaguar; Defensa en la otra Jaguar; Líder en la Pitón.",
                  "13 jugadores con Esquivar de base; 2 ayudantes del entrenador.",
                  "Tier 2 igual en BETA y FINAL (1070k / 140k / 20k): la lista se mantiene."]),
    dict(slug="skavens", name="Skavens", img="skavens.webp",
         fuente=f"{_ANDY}; mismo tier y presupuesto en FINAL, sin cambios.",
         rr=3, apo=True, ac=2,
         players=[("Rata Ogro", 1, ["Imparable"]), ("Blitzer", 2, ["Abrirse paso"]), ("Gutter Runner", 2, ["Forcejear"]),
                  ("Linemen", 3, ["Forcejear"]), ("Linemen", 4, [])],
         tactica=["Forcejear en Gutter Runners y 3 Linemen; Abrirse paso en los Blitzers; Rata Ogro con Imparable.",
                  "3 segundas oportunidades baratas (50k) y 2 ayudantes.",
                  "Tier 2 igual en BETA y FINAL: la lista se mantiene."]),
    dict(slug="habitantes-inframundo", name="Habitantes del Inframundo", img="habitantes-inframundo.webp",
         fuente=f"{_ANDY}, ajustada con el cambio que propone el propio AndyDavo.",
         rr=2, apo=False, induc=[("Sobornos", 1), ("Amañafaltas", 1)],
         players=[("Rata Ogro", 1, ["Imparable"]), ("Gutter Runner", 1, ["Echarse a un lado", "Dos cabezas"]),
                  ("Skaven Blitzer", 1, ["Golpe mortífero"]), ("Skaven Thrower", 1, ["Líder"]),
                  ("Skaven Clanrat (Línea)", 1, ["Forcejear"]), ("Skaven Clanrat (Línea)", 1, ["Jugar sucio"]),
                  ("Skaven Clanrat (Línea)", 1, []), ("Goblin Línea", 5, []), ("Snotling Línea", 3, [])],
         tactica=["Rata Ogro con Imparable y Gutter Runner con Echarse a un lado + Dos cabezas: piezas de one-turn.",
                  "Plan de faltas: Soborno + Amañafaltas (precio con Sobornos y corrupción) y Jugar sucio en un Clanrat.",
                  "Cambio: el Skaven Blitzer pasa de Placaje defensivo a Golpe mortífero, como sugiere AndyDavo; los 10k que sobraban de Flowing lo pagan."]),
    dict(slug="elfos-oscuros", name="Elfos Oscuros", img="elfos-oscuros.webp",
         fuente=f"{_ANDY}; mismo tier y presupuesto en FINAL, sin cambios.",
         rr=2, apo=True,
         players=[("Bruja Elfa", 2, ["Forcejear"]), ("Elfo Oscuro Blitzer", 2, ["Esquivar"]),
                  ("Elfo Oscuro Asesino", 1, ["Esquivar"]), ("Elfo Oscuro Runner", 1, ["Líder"]),
                  ("Elfo Oscuro Línea", 2, ["Forcejear"]), ("Elfo Oscuro Línea", 3, [])],
         tactica=["Esquivar en Blitzers y Asesino; Forcejear en Brujas y 2 Líneas; Runner con Líder.",
                  "Los 30k de Flowing van íntegros a Skill Gold (190k); sobran 5k de equipo.",
                  "Tier 3 igual en BETA y FINAL: la lista se mantiene."]),
    dict(slug="altos-elfos", name="Altos Elfos", img="altos-elfos.webp",
         fuente=f"{_ANDY}, con el ajuste de [Artemis Black — Road to Eurobowl 2026](https://www.youtube.com/watch?v=yI7pBwzeecE) (sept. 2026).",
         rr=2, apo=True, ac=1,
         players=[("Alto Elfo Dragon Warrior", 2, ["Esquivar"]),
                  ("Alto Elfo White Lion Blitzer", 1, ["Esquivar", "Placaje defensivo"]),
                  ("Alto Elfo White Lion Blitzer", 1, ["Esquivar"]),
                  ("Alto Elfo Phoenix Prince Thrower", 1, ["Líder"]),
                  ("Alto Elfo Línea", 1, ["Forcejear"]), ("Alto Elfo Línea", 5, [])],
         tactica=["Esquivar en los 2 Dragon Warriors y los 2 White Lions, Líder en el Phoenix; 2 segundas oportunidades + apotecario + ayudante (patrón de Artemis Black).",
                  "Cambio: el stack del White Lion pasa de Esquivar + Robar balón a Esquivar + Placaje defensivo, la preferencia de Artemis Black; mismo coste (60k).",
                  "Tier 3 igual en BETA y FINAL: presupuesto y Skill Gold idénticos (Flowing 30k → Skill Gold)."]),
]
